### ISSUE TITLE
Monetdb Conversion of string to blob failed

### ISSUE THREAD

**Issue by andodeki** [MonetDB/MonetDB-Go#3]
MonetDB Database Version

> Welcome to mclient, the MonetDB/SQL interactive terminal (unreleased)
> Database: MonetDB v11.39.17, 'mapi:monetdb://plmsql:50000/propertylisting'
> FOLLOW US on https://twitter.com/MonetDB or https://github.com/MonetDB/MonetDB

_Golang Version: go version go1.17.3 linux/amd64_

**here is the code in go playground https://go.dev/play/p/bApu0avz1nz**

**Comment by MitchellWeg** [comment]
`$2a$10$NB2AjnPIm2GuSuW/l1sS7O./1gWhbEA5GeHnEkBzyCHJKCA5EXpXy`
is not a valid BLOB. Why not save it as a `STRING` instead?
