### ISSUE TITLE
Can't use @ in passwords. Get Invalid DSN message.

### ISSUE THREAD

**Issue by vinifrancosilva** [MonetDB/MonetDB-Go#5]
```
db, err := sql.Open("monetdb", "user:P@sswordWith@@localhost:50000/db")
checkErrFatal(err)
```

This returns Invalid DSN.

I use the same password in MariaDB DSN definition with success.

**Comment by MitchellWeg** [comment]
Hi @vinifrancosilva,
I just pushed a fix for this, can you check if it fixes your issue?

**Comment by vinifrancosilva** [comment]
Works like a charm! Thank you very much.
